import Head from 'next/head'
import CustomerInteracting from '../components/home/CustomerInteracting'
import Gallery from '../components/home/Gallery'
import Hero from '../components/home/Hero'
import Introduce from '../components/home/Introduce'
import ShowType from '../components/home/ShowType'

export default function Home() {

  return (
    <div>
      <Head>
        <title>UzTem Buffe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Hero/>
    <ShowType/>
    <Introduce/>
    <CustomerInteracting />
    <Gallery/>
    </div>
  )
}
