import Head from "next/head";
import styles from '../styles/Menu.module.css'
import Link from "next/link";
import FoodMenu from "../components/menu/FoodMenu";
import { getAllProducts } from "../util/baseUrl";

export default function Menu ({ allProducts }) {
    return(
        <div>
            <Head>
                <title>UzTem Buffe</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.menupage}>
                <Link href="/ordernow" className={styles.ordernowbtn}>
                    <button>Order Now</button>
                </Link>
                <FoodMenu data={allProducts}/>
            </div>
        </div>
    )
}

export async function getServerSideProps(){
    const response = await getAllProducts()
    return{
      props:{
        allProducts: response.data
      }
    }
  }