import Head from "next/head";
import styles from '../styles/Menu.module.css'
import data from '../components/dummyProducts.json'
import Link from "next/link";
import FoodMenu from "../components/menu/FoodMenu";

export default function Menu () {
    return(
        <div>
            <Head>
                <title>UzTem Buffe</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.menupage}>
                <Link href="/ordernow" className={styles.ordernowbtn}>
                    <button>Order Now</button>
                </Link>
                <FoodMenu data={data}/>
            </div>
        </div>
    )
}