import Head from 'next/head'
import React from 'react'
import OrdersList from '../../components/ordernow/OrdersList'
import styles from '../../styles/ordernow/ordernow.module.css'
import { getAllProducts } from '../../util/baseUrl'

const OrderNow = ({ productsList }) => {

  const meals = productsList?.filter(product=> product.type === "meal")
  const sideMeals = productsList?.filter(product=> product.type === "side")
  const desserts = productsList?.filter(product=> product.type === "dessert")
  const drinks = productsList?.filter(product=> product.type === "drink")

  return (
    <div>
     <Head>
        <title>UzTem Buffe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.ordernow}>

        <header className={styles.ordernowintro}>
          <h3>Delicious Meals Waiting For Your Order!</h3>
        </header>

       <OrdersList headerText="Meals" itemsList={meals} />        
       <OrdersList headerText="Side Meals" itemsList={sideMeals} />        
       <OrdersList headerText="Deserts" itemsList={desserts} />        
       <OrdersList headerText="Drinks" itemsList={drinks} />

      </section>
    </div>
  )
}

export async function getServerSideProps(){
  const response = await getAllProducts()
  return{
    props:{
      productsList: response.data
    }
  }
}

export default OrderNow